export enum TechImageLink {
  Material = "https://img.icons8.com/color/48/material-ui.png",
  TypeScript = "https://img.icons8.com/color/48/null/typescript.png",
  JavaScript = "https://img.icons8.com/fluency/48/null/javascript.png",
  HTML5 = "https://img.icons8.com/arcade/64/null/html-5.png",
  CSS = "https://img.icons8.com/color/48/null/css3.png",
  SASS = "https://img.icons8.com/color/48/null/sass.png",
  TailWindCSS = "https://img.icons8.com/color/48/null/tailwindcss.png",
  Bootstrap = "https://img.icons8.com/color/48/null/bootstrap.png",
  MongoDB = "https://img.icons8.com/color/48/null/mongodb.png",
  MySQL = "https://img.icons8.com/fluency/48/null/mysql-logo.png",
  ExpressJS = "https://img.icons8.com/officel/40/express-js.png",
  NestJS = "https://img.icons8.com/color/48/nestjs",
  Angular = "https://img.icons8.com/fluency/48/null/angularjs.png",
  Jest = "https://img.icons8.com/external-tal-revivo-color-tal-revivo/48/external-jest-can-collect-code-coverage-information-from-entire-projects-logo-color-tal-revivo.png",
  React = "https://img.icons8.com/color/48/null/react-native.png",
  NodeJS = "https://img.icons8.com/color/48/null/nodejs.png",
  AWS = "https://img.icons8.com/color/48/null/amazon-web-services.png",
  GraphQL = "https://img.icons8.com/color/48/null/graphql.png",
  GitBash = "https://img.icons8.com/color/48/null/git.png",
  GitHub = "https://img.icons8.com/nolan/64/github.png",
  BitBucket = "https://img.icons8.com/color/48/bitbucket.png",
  Jira = "https://img.icons8.com/color/48/jira.png",
  Confluence = "https://img.icons8.com/color/48/atlassian-confluence.png",
  Firebase = "https://img.icons8.com/color/48/null/firebase.png",
}

export enum TechName {
  Material = "Material",
  TypeScript = "TypeScript",
  JavaScript = "JavaScript",
  HTML5 = "HTML5",
  CSS = "CSS",
  SASS = "SASS",
  TailWindCSS = "TailWindCSS",
  Bootstrap = "Bootstrap",
  MongoDB = "MongoDB",
  MySQL = "MySQL",
  ExpressJS = "ExpressJS",
  NestJS = "NestJS",
  Angular = "Angular2+",
  React = "React",
  Jest = "Jest",
  NodeJS = "NodeJS",
  AWS = "AWS",
  GraphQL = "GraphQL",
  GitBash = "GitBash",
  GitHub = "GitHub",
  BitBucket = "BitBucket",
  Jira = "Jira",
  Confluence = "Confluence",
  Firebase = "Firebase",
}
